#!/bin/bash
# This is a config file for Cubuntu Builder: Terminal build script.
# You shouldn't need to change anything expect distro name, version, architecture, edition.

# Distro name. Defaults to 'cubuntu';
# This will be the name of the directory created on your CD/USB, which
# will contain everything including boot files and such.
# For example, Slax changes it to 'slax'.
# Must not contain any spaces.
# If you change it, you must run ./tools/isolinux.bin.update script
# in order to update isolinux.bin for CD booting.
# If you do not need booting from CD (eg you're booting only from USB)
# then you can ignore recompiling isolinux.bin, just rename distro name,
# and you're done.
DISTRONAME="cubuntu"

# Kernel file, will be copied to your Live CD
# Your kernel must support aufs and squashfs. Debian Jessie's kernel is ready
# out of the box.
VMLINUZ=/boot/vmlinuz

# Kernel version. Change it to "3.2.28" for example, if you are building
# Live CD with a different kernel than the one you are actually running
KERNEL=$(uname -r)

# Architecture. Change to the example (x64, x86, 64, 86, x86_64)
# that will your Linux distribution placed in the ISO.
# Defaults will be 'x86_64'.
ARCH="x86_64"

# List of directories for root filesystem
# No subdirectories are allowed, no slashes,
# so You can't use /var/tmp here for example
# Exclude directories like proc sys tmp
MKMOD="bin etc home lib lib64 opt root sbin srv usr var"

# If you require network support in initrd, for example to boot over
# PXE or to load data using 'from' boot parameter from a http server,
# you will need network modules included in your initrd.
# This is disabled by default since most people won't need it.
# To enable, set to true
NETWORK=false

# Temporary directory to store Linux distribution data filesystem
DISTRODATA=/tmp/$DISTRONAME-data

# Bundle extension, for example 'sb' for .sb extension
BEXT=sb

# Directory with kernel .ko modules, can be different in some distros
LMK="lib/modules/$KERNEL"

# Edition, will be ("desktop" or "server" or "terminal").
# Default is to 'desktop'.
EDITION="desktop"

# Version, that version in your Linux distribution.
# For example: (18.04, 20.04, 1.0). Default: 22.11
VERSION="22.11"
